import 'package:flutter/material.dart';
import 'package:kz_core/kz_core.dart';

/// {{name.pascalCase()}} widget.
/// Generated by widget_brick.
///
/// Keep the root layout elastic. Use LayoutBuilder, Wrap, Expanded or Flexible.
/// Avoid static widths/heights in the top-level container.
class {{name.pascalCase()}}Widget extends StatelessWidget {
  const {{name.pascalCase()}}Widget({super.key});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        return Container(
          width: constraints.maxWidth,
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            border: Border.all(color: Colors.white10),
            color: Colors.white.withValues(alpha: 0.02),
          ),
          child: const Text(
            '{{name.titleCase()}}',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.white70,
              fontFamily: 'Courier',
              fontSize: 14,
            ),
          ),
        );
      },
    );
  }
}
