name: kz_domain
description: Motor SRS puro, validadores de input, cálculo de Tiers. Cero dependencias de Flutter — Dart puro.

publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  freezed_annotation: ^3.0.0
  kz_core:
    path: ../kz_core
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  freezed: ^3.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  test: ^1.25.8
