import 'package:riverpod_annotation/riverpod_annotation.dart';

part '{{name}}_provider.g.dart';

/// {{name.pascalCase()}} provider.
/// Generated by provider_brick.
///
/// Rules:
/// - Keep business logic here.
/// - Cancel timers/subscriptions in [dispose].
/// - Provide a [reset] method to return to the initial state.
@riverpod
class {{name.pascalCase()}}Notifier extends _${{name.pascalCase()}}Notifier {
  @override
  bool build() {
    ref.onDispose(() {
      // Clean up timers, listeners, or subscriptions here.
    });
    return false;
  }

  void reset() => state = false;
}
