import 'package:flutter/material.dart';

/// Main widget for the {{name}} feature.
/// Generated by feature_brick.
class {{name.pascalCase()}}Widget extends StatelessWidget {
  const {{name.pascalCase()}}Widget({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox.shrink();
  }
}
