import 'package:flutter/material.dart';
import 'package:kz_core/kz_core.dart';

/// Main widget for the {{name}} feature.
/// Generated by feature_brick.
///
/// Must be fully elastic: use LayoutBuilder, Wrap, Expanded or Flexible.
/// No static widths/heights in the root container.
class {{name.pascalCase()}}Widget extends StatelessWidget {
  const {{name.pascalCase()}}Widget({super.key});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        return Center(
          child: Text(
            '{{name.titleCase()}}',
            style: const TextStyle(
              color: Colors.white70,
              fontSize: 18,
              fontFamily: 'Courier',
            ),
          ),
        );
      },
    );
  }
}
