import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../domain/{{name}}_state.dart';

part '{{name}}_provider.g.dart';

/// Provider for the {{name}} feature.
/// Generated by feature_brick — implement business logic here.
///
/// Rules:
/// - Keep side-effects (timers, DB writes) inside this notifier.
/// - Cancel timers and subscriptions in [dispose].
/// - Reset state to initial values when the feature session ends.
@riverpod
class {{name.pascalCase()}}Notifier extends _${{name.pascalCase()}}Notifier {
  @override
  {{name.pascalCase()}}State build() => const {{name.pascalCase()}}State();

  void reset() => state = const {{name.pascalCase()}}State();
}
