import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../domain/{{name}}_state.dart';

part '{{name}}_provider.g.dart';

/// Provider for the {{name}} feature.
/// Generated by feature_brick — implement business logic here.
@riverpod
class {{name.pascalCase()}}Notifier extends _${{name.pascalCase()}}Notifier {
  @override
  {{name.pascalCase()}}State build() => const {{name.pascalCase()}}State();
}
