import 'package:freezed_annotation/freezed_annotation.dart';

part '{{name}}_state.freezed.dart';

/// Immutable state for the {{name}} feature.
/// Generated by feature_brick.
@freezed
class {{name.pascalCase()}}State with _${{name.pascalCase()}}State {
  const factory {{name.pascalCase()}}State() = _{{name.pascalCase()}}State;
}
