import 'package:freezed_annotation/freezed_annotation.dart';

part '{{name}}_state.freezed.dart';

/// Immutable state for the {{name}} feature.
/// Generated by feature_brick.
///
/// Keep this class pure: no Flutter, no DB, no framework dependencies.
@freezed
abstract class {{name.pascalCase()}}State with _${{name.pascalCase()}}State {
  const factory {{name.pascalCase()}}State({
    @Default(false) bool isLoading,
    @Default(false) bool isSuccess,
    String? errorMessage,
  }) = _{{name.pascalCase()}}State;
}
