import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:kz_core/kz_core.dart';
import 'package:kz_ui_components/kz_ui_components.dart';
import '../providers/{{name}}_provider.dart';

/// Screen for the {{name.pascalCase()}} feature with Cyber-Zen design.
/// Generated by feature_brick.
class {{name.pascalCase()}}Screen extends ConsumerWidget {
  const {{name.pascalCase()}}Screen({super.key});

  static const routePath = '/{{name}}';

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final settings = ref.watch(settingsProvider);
    final accent = settings.accentColor == CyberAccent.green
        ? CyberTheme.defaultAccent
        : CyberTheme.errorRed;

    final state = ref.watch({{name.camelCase()}}NotifierProvider);

    return Scaffold(
      backgroundColor: Colors.black, // Pure OLED black
      body: SafeArea(
        child: Column(
          children: [
            // Header Bar
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              child: Row(
                children: [
                  GestureDetector(
                    onTap: () => Navigator.of(context).pop(),
                    child: Icon(Icons.arrow_back_ios, color: accent, size: 20),
                  ),
                  const SizedBox(width: 16),
                  Text(
                    '{{name.upperCase()}} ENGINE',
                    style: TextStyle(
                      color: accent,
                      fontFamily: 'Courier',
                      fontSize: 14,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 2,
                    ),
                  ),
                ],
              ),
            ),
            const Divider(color: Colors.white10, height: 1),

            // Main Viewport
            Expanded(
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      '{{name.titleCase()}} Screen',
                      style: const TextStyle(
                        color: Colors.white70,
                        fontSize: 18,
                        fontFamily: 'Courier',
                      ),
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'STATE: $state',
                      style: TextStyle(
                        color: accent.withValues(alpha: 0.5),
                        fontSize: 11,
                        fontFamily: 'Courier',
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
