import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:kz_core/kz_core.dart';
import 'package:kz_ui_components/kz_ui_components.dart';
import '../providers/{{name}}_provider.dart';
import 'widgets/{{name}}_widget.dart';

/// Screen for the {{name.pascalCase()}} feature with Cyber-Zen design.
/// Generated by feature_brick.
class {{name.pascalCase()}}Screen extends ConsumerWidget {
  const {{name.pascalCase()}}Screen({super.key});

  static const routePath = '/{{name}}';

  Color _accentColor(CyberAccent accent) {
    return switch (accent) {
      CyberAccent.green => CyberTheme.defaultAccent,
      CyberAccent.red => CyberTheme.errorRed,
      CyberAccent.orange => Colors.orange,
      CyberAccent.blue => Colors.cyanAccent,
      CyberAccent.purple => Colors.purpleAccent,
      CyberAccent.white => Colors.white,
    };
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final settings = ref.watch(settingsProvider);
    final accent = _accentColor(settings.accentColor);
    final state = ref.watch({{name.camelCase()}}NotifierProvider);

    return Scaffold(
      resizeToAvoidBottomInset: true,
      backgroundColor: Colors.black,
      body: SafeArea(
        child: Column(
          children: [
            // Header Bar
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              child: Row(
                children: [
                  GestureDetector(
                    onTap: () => Navigator.of(context).pop(),
                    child: Icon(Icons.arrow_back_ios, color: accent, size: 20),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Text(
                      '{{name.upperCase()}} ENGINE',
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                        color: accent,
                        fontFamily: 'Courier',
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 2,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const Divider(color: Colors.white10, height: 1),

            // Main Viewport — elastic, no static sizes
            Expanded(
              child: LayoutBuilder(
                builder: (context, constraints) {
                  return SingleChildScrollView(
                    child: ConstrainedBox(
                      constraints: BoxConstraints(minHeight: constraints.maxHeight),
                      child: IntrinsicHeight(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            {{name.pascalCase()}}Widget(),
                            const SizedBox(height: 12),
                            Text(
                              'STATE: $state',
                              style: TextStyle(
                                color: accent.withValues(alpha: 0.5),
                                fontSize: 11,
                                fontFamily: 'Courier',
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
